name: advent_of_code_2020
description: Solutions for Advent of Code 2020.
version: 0.0.1

environment:
  sdk: "^3.8.0"

dependencies:
  equatable: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.0
