name: advent_of_code_2020
description: Solutions for Advent of Code 2020.
version: 0.0.1
homepage: http://www.archlinux.dk
author: Jacob Bang <julemand101@archlinux.dk>

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0

dev_dependencies:
  extra_pedantic: ^1.3.0
  test: ^1.16.5
